G_COAL=100
G_GRAVEL=80
G_BOX_Y=80
G_BOX_G=90
G_BOX_B=110
G_METAL=800

CAP_WAGON_3=6
CAP_WAGON_2=4
CAP_WAGON_1=2
CAP_PLAT_3=3
CAP_PLAT_2=2
CAP_PLAT_1=1

REPAIR_LOCO=400
REPAIR_WAGON=300

CREDIT_GIVE=3000
CREDIT_PAY=4000

CONTRACTS = [
    {
        "id": "P1",
        "origin": "A",
        "destination": "B",
        "max_rounds": 3,
        "goods_1": "Уголь",
        "qty_1": 5,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P2",
        "origin": "A",
        "destination": "B",
        "max_rounds": 3,
        "goods_1": "Щебень",
        "qty_1": 6,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P3",
        "origin": "B",
        "destination": "A",
        "max_rounds": 3,
        "goods_1": "Желтый",
        "qty_1": 6,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P4",
        "origin": "A",
        "destination": "B",
        "max_rounds": 3,
        "goods_1": "Синий",
        "qty_1": 3,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P5",
        "origin": "B",
        "destination": "A",
        "max_rounds": 3,
        "goods_1": "Зеленый",
        "qty_1": 4,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P6",
        "origin": "B",
        "destination": "A",
        "max_rounds": 3,
        "goods_1": "Уголь",
        "qty_1": 4,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P7",
        "origin": "A",
        "destination": "B",
        "max_rounds": 3,
        "goods_1": "Щебень",
        "qty_1": 5,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "P8",
        "origin": "A",
        "destination": "B",
        "max_rounds": 3,
        "goods_1": "Уголь",
        "qty_1": 2,
        "goods_2": "Желтый",
        "qty_2": 3,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M1",
        "origin": "A",
        "destination": "B",
        "max_rounds": 2,
        "goods_1": "Уголь",
        "qty_1": 6,
        "goods_2": "Желтый",
        "qty_2": 6,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M2",
        "origin": "B",
        "destination": "A",
        "max_rounds": 2,
        "goods_1": "Щебень",
        "qty_1": 9,
        "goods_2": "Синий",
        "qty_2": 3,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M3",
        "origin": "A",
        "destination": "B",
        "max_rounds": 2,
        "goods_1": "Зеленый",
        "qty_1": 10,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M4",
        "origin": "A",
        "destination": "B",
        "max_rounds": 2,
        "goods_1": "Уголь",
        "qty_1": 6,
        "goods_2": "Щебень",
        "qty_2": 4,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M5",
        "origin": "B",
        "destination": "A",
        "max_rounds": 2,
        "goods_1": "Синий",
        "qty_1": 6,
        "goods_2": None,
        "qty_2": 0,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M6",
        "origin": "A",
        "destination": "B",
        "max_rounds": 2,
        "goods_1": "Уголь",
        "qty_1": 10,
        "goods_2": "Зеленый",
        "qty_2": 4,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M7",
        "origin": "B",
        "destination": "A",
        "max_rounds": 2,
        "goods_1": "Щебень",
        "qty_1": 12,
        "goods_2": "Желтый",
        "qty_2": 6,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "M8",
        "origin": "A",
        "destination": "B",
        "max_rounds": 2,
        "goods_1": "Щебень",
        "qty_1": 6,
        "goods_2": "Желтый",
        "qty_2": 6,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "S1",
        "origin": "A",
        "destination": "B",
        "max_rounds": 1,
        "goods_1": "Металл",
        "qty_1": 1,
        "goods_2": "Уголь",
        "qty_2": 6,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "S2",
        "origin": "B",
        "destination": "A",
        "max_rounds": 1,
        "goods_1": "Металл",
        "qty_1": 2,
        "goods_2": "Щебень",
        "qty_2": 6,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "S3",
        "origin": "A",
        "destination": "B",
        "max_rounds": 1,
        "goods_1": "Зеленый",
        "qty_1": 6,
        "goods_2": "Синий",
        "qty_2": 6,
        "goods_3": None,
        "qty_3": 0,
    },
    {
        "id": "S4",
        "origin": "A",
        "destination": "B",
        "max_rounds": 1,
        "goods_1": "Металл",
        "qty_1": 2,
        "goods_2": "Зеленый",
        "qty_2": 4,
        "goods_3": "Щебень",
        "qty_3": 4,
    },
]
